theme: jekyll-theme-cayman
title: "Linked Data for the Humanities: methods and techniques"
description: "Half-day Tutorial to be held at the Digital Humanities Conference DH2019 in Utrecht, 8th July 2019 from 14.00pm."
show_downloads: false
show_view_on_github: false
