theme: jekyll-theme-cayman
title: "Linked Data for the Humanities: methods and techniques"
description: "Introduction, agenda, and resources for the half-day Tutorial Linked Data for the Humanities: Methods and Techniques, to be held at the Digital Humanitiers Conference DH2019 in Utrecht, 8th July 2019 from 14.00pm."
show_downloads: false
